### ISSUE TITLE
Documentation Missing

### ISSUE THREAD

**Issue by gabriel-vanca** [data-enabler/streamdeck-profile-generator#1]
Hi,

Could you please add documentation on how to use this tool?

**Comment by samjco** [comment]
+1

**Comment by nectak** [comment]
yes please

**Comment by data-enabler** [comment]
Improved the documentation a bit in the main readme file. This is more of a library than a standalone tool, so some experience writing JavaScript is going to be needed to use it, but hopefully this helps
